# Generated by Django 3.2.7 on 2021-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Заголовок (УЗБ)')),
                ('description_uz', models.TextField(verbose_name='Описание (УЗБ)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (АНГ)')),
                ('description_en', models.TextField(verbose_name='Описание (АНГ)')),
                ('img', models.ImageField(upload_to='media', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='metatags',
            name='title_en',
            field=models.CharField(default='', max_length=300, verbose_name='Title (АНГ)'),
        ),
    ]
