# Generated by Django 3.2.7 on 2021-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatags',
            name='title_en',
            field=models.CharField(default='', max_length=300, verbose_name='Title (АНГ)'),
        ),
    ]
