# Generated by Django 3.2.7 on 2021-09-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_metatags_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('work', models.CharField(max_length=100, verbose_name='Должность')),
                ('name_lat', models.CharField(max_length=100, verbose_name='Имя (на Латинице)')),
                ('surname_lat', models.CharField(max_length=100, verbose_name='Фамилия (на Латинице)')),
                ('work_lat', models.CharField(max_length=100, verbose_name='Должность (на Латинице)')),
                ('img', models.ImageField(upload_to='media', verbose_name='Фото')),
            ],
        ),
    ]
