# Generated by Django 3.2.7 on 2021-09-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Человека', 'verbose_name_plural': 'Люди'},
        ),
    ]
