# Generated by Django 3.2.7 on 2021-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_metatags_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='title_en',
            field=models.CharField(max_length=300, verbose_name='Title (АНГ)'),
        ),
    ]
