# Generated by Django 3.2.7 on 2021-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (АНГ)'),
        ),
    ]
